# Generated by Django 5.1.6 on 2025-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
